### ISSUE TITLE
Reset password API

### ISSUE THREAD

**Issue by ravi9994** [thedarkkid/laravel_api_framework#3]
@thedarkkid great work, I'm finding routes for reset password but not found in api.php
please let me know how to call forgot and reset password API

**Comment by thedarkkid** [comment]
Hi, sorry for the super late reply, I took some time off to focus on other things. You can find the routes for password reset by running
`php artisan route:list` and looking for the password reset route. I'd post an image of it now

**Comment by thedarkkid** [comment]
![Screenshot (128)](https://user-images.githubusercontent.com/40186891/90333501-5aa5cf00-dfd7-11ea-9bc1-b8a63c849fc6.png)
Here is the screenshot of all the reset password routes
